# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [START jenkins_deployment]
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: mortum5/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        securityContext:
          privileged: true
        env:
        - name: JENKINS_OPTS
          valueFrom:
            secretKeyRef:
              name: jenkins-creds
              key: options
        - name: JENKINS_OPTS
          value: '-Djenkins.install.runSetupWizard=false'
        - name: JAVA_OPTS
          value: '-Xmx1024m'
        resources:
          limits:
            cpu: 1000m
            memory: 1500Mi
          requests:
            cpu: 1000m
            memory: 1500Mi
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
          - name: ssh-key-gitlab
            mountPath: /var/jenkins_home/ssh_key
          - name: docker-hub
            mountPath: /var/jenkins_home/docker_hub
          - mountPath: /var/run/docker.sock
            name: docker-sock
      volumes:
        - name: jenkins-home
          emptyDir: {}
        - name: ssh-key-gitlab
          secret:
            secretName: ssh-key-gitlab
        - name: docker-hub
          secret:
            secretName: docker-hub
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        #gcePersistentDisk:
        #  pdName: jenkins-home
        #  fsType: ext4
        #  partition: 1
# [END jenkins_deployment]
